name: CI
on:
  schedule: [{cron: '0 0 * * *'}]
  push: {branches: master}
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: omelkonian/setup-agda@master
        with:
          agda-version: 2.6.2.2.20221128
          stdlib-version: 1.7.2-rc1
          main: Prelude/Main
          token: ${{ secrets.GITHUB_TOKEN }}
          measure-typechecking: true
          ribbon: true
