name: CI
on:
  # schedule: [{cron: '0 0 * * *'}]
  push: {branches: master}
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: omelkonian/setup-agda@master
        with:
          agda-version: 2.8.0
          stdlib-version: 2.3
          main: Prelude/Main
          token: ${{ secrets.GITHUB_TOKEN }}
          measure-typechecking: true
          ribbon: true
