name: build-deploy
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - master
jobs:
  built-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.1
      - uses: omelkonian/setup-agda@master
        with:
          agda-version: '2.6.1'
          stdlib-version: '1.3'
          main: Prelude/Main
          token: ${{ secrets.GITHUB_TOKEN }}

